#!/bin/sh

echo "\n- Pip (pip)"
pip install --upgrade --no-use-wheel pip

echo "\n- Pip (setuptools)"
pip install --upgrade --no-use-wheel setuptools

echo "\n- Pip (outdated)"
echo Skipped.
#pip list --outdated --allow-external vboxapi | cut -d " " -f 1 | xargs pip install -U
